module.exports = {
  rules: {
    // "require-author": "error",
    // "require-description": "error",
    // "require-engines": "error",
    "require-license": "error",
    "require-name": "error",
    // "require-repository": "error",
    "require-version": "error",
    // "require-bugs": "error",
    // "require-homepage": "error",
    // "require-keywords": "error",
    "bin-type": "error",
    "config-type": "error",
    "description-type": "error",
    "devDependencies-type": "error",
    "directories-type": "error",
    "engines-type": "error",
    "files-type": "error",
    "homepage-type": "error",
    "keywords-type": "error",
    "license-type": "error",
    "main-type": "error",
    "man-type": "error",
    "name-type": "error",
    "preferGlobal-type": "error",
    "private-type": "error",
    "repository-type": "error",
    "scripts-type": "error",
    "version-type": "error",
    "valid-values-license": ["error", ["UNLICENSED"]],
    // "valid-values-author": ["error", ["Thomas Lindner"]],
    "valid-values-name-scope": ["error", ["@repo"]],
    "valid-values-private": ["error", [true]],
    "no-duplicate-properties": "error",
    "no-restricted-dependencies": ["error", ["gulping-npm-package-json-lint"]],
    "no-restricted-pre-release-dependencies": [
      "error",
      ["gulping-npm-package-json-lint"],
    ],
    "no-restricted-devDependencies": [
      "error",
      ["gulping-npm-package-json-lint"],
    ],
    "no-restricted-pre-release-devDependencies": [
      "error",
      ["gulping-npm-package-json-lint"],
    ],
    "name-format": "error",
    "version-format": "error",
    "prefer-property-order": [
      "error",
      // from: https://github.com/keithamus/sort-package-json/blob/93a1cbcfbc3b7cacd8a93784c61d3b8db8fa23be/index.js#L186
      [
        "$schema",
        "name",
        "displayName",
        "version",
        "private",
        "description",
        "categories",
        "keywords",
        "homepage",
        "bugs",
        "repository",
        "funding",
        "license",
        "qna",
        "author",
        "maintainers",
        "contributors",
        "publisher",
        "sideEffects",
        "type",
        "imports",
        "exports",
        "main",
        "svelte",
        "umd:main",
        "jsdelivr",
        "unpkg",
        "module",
        "source",
        "jsnext:main",
        "browser",
        "react-native",
        "types",
        "typesVersions",
        "typings",
        "style",
        "example",
        "examplestyle",
        "assets",
        "bin",
        "man",
        "directories",
        "files",
        "workspaces",
        "binary",
        "scripts",
        "betterScripts",
        "contributes",
        "activationEvents",
        "husky",
        "simple-git-hooks",
        "pre-commit",
        "commitlint",
        "lint-staged",
        "nano-staged",
        "config",
        "nodemonConfig",
        "browserify",
        "babel",
        "browserslist",
        "xo",
        "prettier",
        "eslintConfig",
        "eslintIgnore",
        "npmpkgjsonlint",
        "npmPackageJsonLintConfig",
        "npmpackagejsonlint",
        "release",
        "remarkConfig",
        "stylelint",
        "ava",
        "jest",
        "jest-junit",
        "jest-stare",
        "mocha",
        "nyc",
        "c8",
        "tap",
        "resolutions",
        "dependencies",
        "devDependencies",
        "dependenciesMeta",
        "peerDependencies",
        "peerDependenciesMeta",
        "optionalDependencies",
        "bundledDependencies",
        "bundleDependencies",
        "extensionPack",
        "extensionDependencies",
        "flat",
        "packageManager",
        "engines",
        "engineStrict",
        "volta",
        "languageName",
        "os",
        "cpu",
        "preferGlobal",
        "publishConfig",
        "icon",
        "badges",
        "galleryBanner",
        "preview",
        "markdown",
        "prisma",
      ],
    ],
  },
};
